spring.application.name=spicestore
habitat=local

app.baseUrl = http://localhost:4200

spring.datasource.url= jdbc:mysql://localhost:3306/spice_store?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username= root
spring.datasource.password= root

spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto= update

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

# App Properties
app.jwtCookieName= token
app.jwtSecret= NqKQM0U7cS0eW8/oa1fs1Ro0cELYvchi3AJy8V8MpMI=
app.jwtExpirationMs= 86400000

# Actuator
management.endpoints.web.exposure.include=*
info.app.name=Spice Store API
info.app.version=1.0.0

# Email properties
spring.mail.default-encoding=UTF-8
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=chandhrubai1@gmail.com
spring.mail.password=gqgxnklapepisrqy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.test-connection=false
spring.mail.properties.mail.smtp.starttls.required=true

app.redirect.url=http://localhost:4200

# Local file storage
app.upload.dir=uploads
app.upload.max-file-size=5MB

# Razorpay
razorpay.api.key = rzp_test_yourkey
razorpay.api.secret = yoursecret
razorpay.webhook.secret=yourwebhooksecret

# GST Configuration
gst.enabled=true
gst.cgst.rate=9
gst.sgst.rate=9

app.mail.from = Spice Store <noreply@yourstore.com>
