spring.application.name=onlinestore
habitat=dev

spring.datasource.url= ${SPRING_DATASOURCE_URL}
spring.datasource.username= ${SPRING_DATASOURCE_USERNAME}
spring.datasource.password= ${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto= update


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# App Properties
app.jwtCookieName= token
app.jwtSecret= ${APP_JWT_SECRET}
app.jwtExpirationMs= 86400000

logging.level.org.springframework.security=DEBUG
logging.level.com.mindoot=DEBUG


#actuator
management.endpoints.web.exposure.include=*
info.app.name=Spice Store API
info.app.version=1.0.0

# email properties
spring.mail.default-encoding=UTF-8
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.test-connection=false
spring.mail.properties.mail.smtp.starttls.required=true

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB


razorpay.api.key = ${RAZORPAY_API_KEY}
razorpay.api.secret = ${RAZORPAY_API_SECRET}
razorpay.webhook.secret=${RAZORPAY_WEBHOOK_SECRET}

shiprocket.email=${SHIPROCKET_EMAIL}
shiprocket.password=${SHIPROCKET_PASSWORD}
shipRocket.webhook.secret=${SHIPROCKET_WEBHOOK_SECRET}


app.mail.from = Spice Store <noreply@yourstore.com>
JAVA_OPTS=-XX:ReservedCodeCacheSize=128M



